openapi: 3.2.0
info:
  version: 2.6.0
  title: Real Time Payment Credit Transfers Credit Transfers Account…
  description: Truist Financial APIs for Real Time Payments Credit Transfers per ISO 20022
  contact:
    name: Truist API Support
    url: https://developer.truist.com/contact-us
servers:
- url: https://api-sandbox.truist.com/commercial
  description: Truist Financial Commercial Open Banking APIs - Sandbox environment
- url: https://apicert.truist.com/commercial
  description: Truist Financial Commercial Open Banking APIs - Certification environment
- url: https://api.truist.com/commercial
  description: Truist Financial Commercial Open Banking APIs - Production environment
tags:
- name: Credit Transfers Account List
  description: Eligible accounts for Real Time Payment Credit Transfer
paths:
  /v2/payments/rtp/credit-transfers/accounts:
    parameters:
    - $ref: '#/components/parameters/FapiInteractionIdHeader'
    - $ref: '#/components/parameters/AccountStatus'
    get:
      tags:
      - Credit Transfers Account List
      description: Retrieves the list of accounts eligible for credit transfers
      summary: Get accounts
      operationId: getEligibleCreditTransfer
      responses:
        '200':
          description: OK
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/x-fapi-interaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountList'
              example:
                accounts:
                - accountId: kljTRlVDLS9kSqyTlT
                  accountType: CHECKING
                  displayName: '************604836'
                  bankNumber: '102'
                  description: ANALYZED CHECKING
                  eligibilityType: RTP
                  currentAvailableBalance: 20.4
                  status: OPEN
                - accountId: mljLWlVDLS9kSqxTlF
                  accountType: SAVINGS
                  displayName: '************176443'
                  bankNumber: '302'
                  description: BUSINESS 500 SAVINGS
                  eligibilityType: RTP
                  currentAvailableBalance: 20.4
                  status: OPEN
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Forbidden
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/x-fapi-interaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                INSUFFICIENT_SCOPE:
                  value:
                    code: '403'
                    message: Invalid scope
        '404':
          description: Not Found
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/x-fapi-interaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                ACCOUNT_NOT_AVAILABLE:
                  value:
                    code: '8000'
                    message: Accounts not available for the given OnlineId
                RESOURCE_NOT_FOUND:
                  value:
                    code: '1101'
                    message: URI does not represent a recognised resource
        '405':
          description: Method Not Allowed
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/x-fapi-interaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                METHOD_NOT_ALLOWED:
                  value:
                    code: '1206'
                    message: Method Not Allowed
        '429':
          $ref: '#/components/responses/429'
        '500':
          description: Internal Server Error
          headers:
            x-fapi-interaction-id:
              $ref: '#/components/headers/x-fapi-interaction-id'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                INTERNAL_SERVER_ERROR:
                  value:
                    code: '500'
                    message: Internal server error
        '503':
          $ref: '#/components/responses/503'
        '504':
          $ref: '#/components/responses/504'
      security:
      - OAuth:
        - read:accounts
components:
  responses:
    '429':
      description: Too Many Requests
      headers:
        x-fapi-interaction-id:
          $ref: '#/components/headers/x-fapi-interaction-id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            SPIKE_ARREST_VIOLATION:
              value:
                code: '1207'
                message: Too Many Requests
            QUOTA_VIOLATION:
              value:
                code: '1208'
                message: Quota Violation
    '503':
      description: Service unavailable / system down for maintenance
      headers:
        x-fapi-interaction-id:
          $ref: '#/components/headers/x-fapi-interaction-id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            SERVICE_UNAVAILABLE:
              value:
                code: '503'
                message: We are currently unable to process your request due to a system issue
    '504':
      description: Service Timed out
      headers:
        x-fapi-interaction-id:
          $ref: '#/components/headers/x-fapi-interaction-id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            GATEWAY_TIMEOUT:
              value:
                code: '504'
                message: An unexpected error occurred while processing your request
    '401':
      description: Unauthorized
      headers:
        x-fapi-interaction-id:
          $ref: '#/components/headers/x-fapi-interaction-id'
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          examples:
            INVALID_ACCESS_TOKEN:
              value:
                code: '603'
                message: Authentication failed
  schemas:
    AccountList:
      title: Commercial Account List
      description: Accounts returned by API upon successful search
      type: object
      properties:
        accounts:
          type: array
          items:
            $ref: '#/components/schemas/Account'
    Account:
      title: Commercial Account
      description: List of commercial accounts for a user
      type: object
      properties:
        accountId:
          description: Unique identifier for account
          type: string
        accountType:
          $ref: '#/components/schemas/AccountType'
        displayName:
          description: Obfuscated account number for display purpose ex. client app screen
          type: string
        bankNumber:
          description: Bank number to identify the bank branch
          type: string
        description:
          description: Customer created nick name linked to the account
          type: string
        eligibilityType:
          description: Payment type allowed for this account
          $ref: '#/components/schemas/PaymentType'
        currentAvailableBalance:
          description: current available balance
          type: number
        status:
          description: Status of the account
          type: string
          enum:
          - OPEN
          - CLOSED
    Error:
      title: Error
      description: An error entity which can be used at the API level for error responses or at the account level to indicate a problem specific to a particular account
      type: object
      properties:
        code:
          type: string
          description: Long term persistent identifier which can be used to trace error condition back to log information
        message:
          type: string
          description: End user displayable information which might help the customer diagnose an error
    PaymentType:
      title: Schema definition for payment type
      description: TCH Payment type
      type: string
      enum:
      - RTP
    AccountType:
      title: Account Type
      description: Account type identified by the bank
      type: string
      enum:
      - CHECKING
      - SAVINGS
  parameters:
    FapiInteractionIdHeader:
      name: x-fapi-interaction-id
      in: header
      description: Unique request Identifier
      required: false
      schema:
        type: string
      example: rrt-970585410023330903-b-gce-821-23397-1
    AccountStatus:
      name: status
      in: query
      description: Status of the account
      example: OPEN
      schema:
        type: string
        enum:
        - OPEN
        - CLOSED
  headers:
    x-fapi-interaction-id:
      description: Unique request identifier
      required: true
      schema:
        type: string
      example: rrt-970585410023330903-b-gce-821-23397-1
  securitySchemes:
    OAuth:
      type: oauth2
      description: The production authorization URL will be provided after the onboarding process is completed.
      flows:
        authorizationCode:
          authorizationUrl: https://api-sandbox.truist.com/commercial/auth/v1/oauth/authorize
          tokenUrl: https://api-sandbox.truist.com/commercial/auth/v2/oauth/token
          scopes:
            read:payments: Scope required to read payment details
            write:payments: Scope required to create or update payments
            read:accounts: Scope required to read accounts information
